# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59c762632598503378b906ae63d9d8c0f1b2dcf7997e9d7b8550bc2dbf7230be0eed4c9d1f519a0b64b152b973eed4b250198fafa9d0d5f81972fa8a65e620cc

test:
  secret_key_base: 8e25fa745322e75cd5ac943a7dad728fb7af0e9cc3d872f8ad0efa979a3793315ffae1c917272c9511de6ee3ce8bce0c5781086bb4fc67f1917329b51d44aa59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
